### ISSUE TITLE
recalculate swap output when token in/output is changed

### ISSUE THREAD

**Issue by ericDeCourcy** [ericDeCourcy/Fuse-StableSwap-Frontend#30]

**Comment by ericDeCourcy** [comment]
to test this, go to usd1 pool and type in 100 for swap input for a swap from DAI to USDC. Then, in the dropdown menu, change USDC to USDT. It should have the same predicted output. Change 100 -> 10 -> 100, and the output will change to be accurate.

I believe all we need to do is re-calc the estimated output whenever the dropdown menu choices change

**Comment by ericDeCourcy** [comment]
@alanna-larson there's a similar issue where when you change the output token without changing the tokens in number, it won't recalculate

**Comment by ericDeCourcy** [comment]
@alanna-larson there's a similar issue where when you change the output token without changing the tokens in number, it won't recalculate

**Comment by alanna-larson** [comment]
i added the recalc event to both token fields and that case was recalcing
correctly for me, can you describe your exact steps or attach a screen cap
of the issue
