### ISSUE TITLE
Redesign of approvals

### ISSUE THREAD

**Issue by ericDeCourcy** [ericDeCourcy/Fuse-StableSwap-Frontend#32]
Currently, approvals happen on a tab which comes before the "take action" tab.

We want approvals to now be embedded into the take action tab. For example, the "swap" button should change depending on whether the user has approved the token in question or not. If they have not approved the token, it should say "approve" and trigger an approval transaction. Then, once approved, it should trigger a swap transaction when clicked.

This is pretty standard behavior with crypto frontends. Take a look at fuseswap as an example.

This is needed because pretty soon, we're going to have more than 1 pool. It will get confusing, and fast, to have an "approvals" tab with 12 different approvals because we have 3 pools.

**Comment by ericDeCourcy** [comment]
Lets start with the swap button, since this is likely to be the most commonly needed one

When transitioning to the swap tab, or changing the swap input, `updateSwapButton` outlined below should be called (represented in psuedocode):
```
global var swapButtonState;  

enum buttonStates = {
  needsApproval,
  canSwap
};

func updateSwapButton() {
  if(!isSwapInputApproved(tokenIndexIn)) {
    button.innerHTML = "Approve ${tokenIn.name}";
    swapButtonState = needsApproval;
  }
  else {
    button.innerHTML = "Swap";
    swapButtonState = canSwap;
  }
}

func isSwapInputApproved(tokenIndexIn) {
  //use some funcs which already exist to check whether the user has approved the input token
  // return true if approved, false if not
}

func onSwapButtonClick() {
  if(swapButtonState == needsApproval){
    //send a tx to metamask for them to approve the swap
  }
  else {
    // send a tx to metamask to actually conduct the swap
  }
}
```
 
Some questions though:
- can you think of a good way to refactor this?
- do you think, instead of using a "button state" variable, we can just do the same checks within `onSwapButtonClick` and `updateSwapButton`?

**Comment by alanna-larson** [comment]
interactions that require approval:
* deposit -> any token being deposited (non-zero value)
* swap -> input token
* withdrawals -> LP token only
