### ISSUE TITLE
page hangs if not connected to fuse network

### ISSUE THREAD

**Issue by ericDeCourcy** [ericDeCourcy/Fuse-StableSwap-Frontend#42]
To replicate

1. go to the page ericdecourcy.github.io
2. go to metamask and change the menu you're connected to to something other than fuse network
3. click "connect to metamask" on the page

**Comment by ericDeCourcy** [comment]
may be rleated to #28

**Comment by ericDeCourcy** [comment]
https://ethereum.stackexchange.com/questions/86656/how-to-programatically-change-the-current-network-with-metamask

**Comment by ericDeCourcy** [comment]
The metamask docs show how to change the ethereum chain!

https://docs.metamask.io/guide/rpc-api.html#usage-with-wallet-switchethereumchain

**Comment by alanna-larson** [comment]
fuse chain creation fails for me with the following issue in chromium. not sure why as that param is listed in [the docs](https://docs.metamask.io/guide/rpc-api.html#usage-with-wallet-switchethereumchain)

did you test chain creation before pushing? it fails in your version as well (once i get rid of a broken showError call (showError needs an error param))

![image](https://user-images.githubusercontent.com/52585995/147421308-27f908e6-7644-4be1-af05-d5dd620bbc6d.png)
![image](https://user-images.githubusercontent.com/52585995/147421324-ac3bb035-839b-4c32-8995-0d9d28556b12.png)
